### ISSUE TITLE
Share the Configuration Used in the Theme's Screenshots

### ISSUE THREAD

**Issue by KaikSelhorst** [csalmeida/summercamp-vscode-theme#1]
Hello [@csalmeida ]! 😊

Firstly, I want to express how much I love your theme. The screenshots showcase an amazing environment in Visual Studio Code, and many people, myself included, would be interested in replicating the exact same look.

Would it be possible to share the settings you were using at the time of the screenshots? This includes information such as:

    - Icons used
    - Font family
    - Specific theme settings

These details would be extremely helpful for people who want to achieve the same aesthetic. I would be very grateful if you could provide them.

Thank you! 🌟

**Comment by csalmeida** [comment]
Hi @KaikSelhorst,

Thank you, I'm glad you like the look of the theme!

**Comment by csalmeida** [comment]
Hi @KaikSelhorst,

Thank you, I'm glad you like the look of the theme! 

- Icons pack: [Minimal Icons by Jacob Gillespie](https://marketplace.visualstudio.com/items?itemName=jacobwgillespie.minimal-icons) 
- Font family: [Zed Sans by Zed Industries](https://github.com/zed-industries/zed-fonts/tree/main)

For specific team settings there's two values that need to be added/edited in `settings.json`:

```json
{
  "editor.bracketPairColorization.enabled": false,
  "editor.guides.indentation": false
}
```

Please let me know if this helps. 🙏
